%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                              % 
% plot_estimates.m                                                             % 
%                                                                              % 
% This function plots curve fitting estimates from canonical information and   % 
% data generated in the file problem2.m                                        % 
%                                                                              % 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [fhat,var_fhat,f] = plot_estimates(info,estimates,x,y,F,a,sigma2) 
  xx = [0:.01:1]'; % Make a "fine" grid to estimate on
  fhat = F(xx)*estimates.ahat; % Estimate at each point
  var_fhat = sigma2*dot( F(xx)*inv(info.T), F(xx),2 ); % Sigma known
  hat_var_fhat = estimates.hat_sigma2*dot( F(xx)*inv(info.T), F(xx),2 ); % Sigma unknown
  f = plot(x,y,'k.',...
	   xx,F(xx)*a,'b-', ...
	   xx,fhat,'r-',...
	   xx,fhat+2*sqrt(var_fhat),'b:',...
	   xx,fhat-2*sqrt(var_fhat),'b:',...
	   xx,fhat+2*sqrt(hat_var_fhat),'r--',...
	   xx,fhat-2*sqrt(hat_var_fhat),'r--');
  legend({'Data',...
	 sprintf('True parameters: a0=%.2f a1=%.2f',a),...
	 sprintf('Est. parameters: a0=%.2f a1=%.2f',estimates.ahat),...
	 '2 Var $f(\hat{x}) + f(\hat{x})$',...
	 '-2 Var $f(\hat{x}) + f(\hat{x})$',...
	 '2 $\widehat{Var f(\hat{x})} + f(\hat{x})$',...
	 '-2 $\widehat{Var f(\hat{x})} + f(\hat{x})$'},...
	 'Location','Northwest',...
	 'Interpreter','Latex');
  title(sprintf('Estimates for %d points',info.n))

